#!/bin/sh
./configure --host=arm-hisiv400-linux --with-shared --without-manpages
make -j4 > /dev/null
# make install DESTDIR=/home/gjyang/working/fwbuilder/HI3516A/firmwares/rev-k/Ver-4.31/ri_base
# make uninstall
